### ISSUE TITLE
Code review feedback

### ISSUE THREAD

**Issue by dkotter** [10up/simple-google-news-sitemap#12]
Let me know if there's a better place for code review feedback, but seemed like a single issue tracking everything might be easiest.

Also let me know if there's any questions on the following items. I'd see most of these as optional (some even just my opinions) so feel free to push back on anything.

- [x] Both the [`README.md`](https://github.com/10up/simple-google-news-sitemap/blob/1.0.1/README.md#requirements) and [`readme.txt`](https://github.com/10up/simple-google-news-sitemap/blob/1.0.1/readme.txt#L33) files talk about how WP Local Docker is a requirement. Seems like that should be part of the Local Setup section maybe, as that isn't a requirement if you're installing this plugin the normal way
- [x] We should be consistent in the PHP version we require. The [`readme.txt`](https://github.com/10up/simple-google-news-sitemap/blob/1.0.1/readme.txt#L7) and [main plugin file](https://github.com/10up/simple-google-news-sitemap/blob/1.0.1/simple-google-news-sitemap.php#L15) specify PHP 7.4 but the [`composer.json`](https://github.com/10up/simple-google-news-sitemap/blob/1.0.1/composer.json#L15) file says 7.2+
- [x] Any custom hooks (actions or filters) that we have should follow the [WordPress documentation standards](https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/#4-hooks-actions-and-filters)
- [x] In the `Core` class, we load all of our hooks in the [`__construct`](https://github.com/10up/simple-google-news-sitemap/blob/1.0.1/includes/classes/Core.php#L43). While this works, I'd prefer to have an `init` method that loads these instead and then in our main plugin file, after `$plugin_core = new Core();`, run `$plugin_core->init()`. This way we're not coupling our class state with setting up hooks
- [x] We have an [array of post statuses](https://github.com/10up/simple-google-news-sitemap/blob/1.0.1/includes/classes/Core.php#L31) in the `Core` class that we use to determine if status change happens that we need to react to. Wondering if those statuses need wrapped in a filter so others can change those as needed, for instance if they have some custom post statuses?
- [x] In our `Sitemap` class, we get all `public` post types for our supported list. We recently changed this in Distributor to use `array_filter( get_post_types(), 'is_post_type_viewable' )` instead (see https://github.com/10up/distributor/issues/906). Might be worth doing the same here
- [x] Our `Utils` class right now only handles things around caching. Might be worth renaming this something like `CacheUtils` or something similar
- [ ] ~~In our cache handling, we check if `WP_Cache` is defined and then use the cache API, otherwise we use the transient API. Could we not just use the transient API here, as it will automatically use the cache API if it can? Not sure if there's a specific reason we have it set up this way but could potentially simplify code here~~ Opened a [new issue](https://github.com/10up/simple-google-news-sitemap/issues/16) to track this, as it's more of a question
